---
Name: hamaka-userforms-retention
---

SilverStripe\UserForms\Model\UserDefinedForm:
  extensions:
    - Hamaka\UserForms\Model\UserFormRetentionExtension

DNADesign\ElementalUserForms\Model\ElementForm:
  extensions:
    - Hamaka\UserForms\Model\UserFormRetentionExtension




